meta_product_name: "Vamos Barcelona"
meta_title: "Vamos Barcelona - Apoya causas locales en Barcelona con tus amigos"
meta_description: "Encuentre oportunidades de voluntariado en Barcelona e involucrate con tus amigos. Busca y aplica en menos de dos minutos para soportar causas locales."
meta_image: "meta_img.jpg" # should exist in `app/assets/images/`
